### PR TITLE
added cars and adjusted the finish line

### PR DESCRIPTION
**Pull request by srikkar**
Replaced color blocks with Cars,  so you can see colorful cars now in the repo :) 

Adjusted the finish line w.r.to road

### CODE REVIEW

**Comment by srikkar** [comment]
@gilgamesh7 , please add a car racing audio file to enhance the feel.
I have tried few, but left it. You might know better soundtracks

**Comment by gilgamesh7** [comment]
> 

Hey buddy, cant hear the music anymore ? Is it just me ?

**Comment by srikkar** [comment]
Hi, I can hear it. PLease re-check.

Also, please add a new mp3 soundtrack for car race

**Comment by gilgamesh7** [comment]
> 

Yes, hardware issue on my side :) Merged now.

**Pull request merged**
